spring.application.name=GestioneBackOffice
spring.datasource.url=jdbc:postgresql://localhost:5432/backtalamonese
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
# MULTIPART (upload file)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ADMIN CREDENTIALS // usa variabili d'ambiente in produzione
admin.username=admin
admin.password=latuapassword
# JWT
jwt.secret=chiavesegretamoltolungadialmeno32caratteri!!
jwt.expiration=86400000
# CLOUDINARY - usa variabili d'ambiente in produzione
cloudinary.cloud-name=dqeq7nvtt
cloudinary.api-key=411846723479259
cloudinary.api-secret=55WlkOtA7RkwDDXxQ5vIhbx2o1M