spring.application.name=GestioneBackOffice
spring.datasource.url=jdbc:postgresql://localhost:5432/backtalamonese
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
# MULTIPART (upload file)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ADMIN CREDENTIALS // usa variabili d'ambiente in produzione
admin.username=${ADMIN_USERNAME:admin}
admin.password=${ADMIN_PASSWORD:changename}
# JWT
jwt.secret=${JWT_SECRET:chiavesegretamoltolungadialmeno32caratteri!!}
jwt.expiration=86400000
# CLOUDINARY - usa variabili d'ambiente in produzione
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:tuocloudname}
cloudinary.api-key=${CLOUDINARY_API_KEY:tuoapikey}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:tuoapisecret}